Backend/Backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    homepage,
)

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/accounts/urls.py
from django.urls import path, include

from .views import (
    profile,
    change_pw,
)

app_name = 'accounts'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('password/', change_pw, name='change_pw'),
]

Backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager

# Create your models here.
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    nickname = models.CharField(unique=False, max_length=100, null=True, blank=True, default='no username')
    profile_img = models.ImageField(upload_to='uploads/profile_img/', null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

Backend/accounts/forms.py
from django import forms
from allauth.account.forms import LoginForm, SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm

class MyCustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(MyCustomLoginForm, self).__init__(*args, **kwargs)

        self.fields['login'].label = False
        self.fields['login'].widget.attrs.update({
            'class': 'form-control',
            'id': 'user-email',
            'placeholder': 'Email'
        })

        self.fields['password'].label = False
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'id': 'user-password',
            'placeholder': 'Password'
        })

        self.fields['remember'].widget.attrs.update({
            'id': 'remember-checkbox',
        })
    
    
class MyCustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(MyCustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = False
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'id': 'user-email',
            'placeholder': 'Email'
        })

        self.fields['password1'].label = False
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'id': 'user-password',
            'placeholder': 'Password'
        })

        self.fields['password2'].label = False
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'id': 'user-confirm-password',
            'placeholder': 'Confirm Password'
        })

        self.fields['nickname'] = forms.CharField(
            required=False,
            label=False,
            widget=forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'user-nickname',
                    'placeholder': 'Username (optional)'
                }
            )
        )

    def save(self, request):
        nickname = self.cleaned_data.get('nickname')
        user = super(MyCustomSignupForm, self).save(request)
        if nickname == '':
            print('## no nickname set')
            user.nickname = 'no username'
            user.save()
        print('## new user signup:', user)
        return user
    
    
class MyCustomSocialSignupForm(SocialSignupForm):
    def __init__(self, *args, **kwargs):
        super(MyCustomSocialSignupForm, self).__init__(*args, **kwargs)

        self.fields['email'].label = False
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'id': 'user-email',
            'placeholder': 'Email'
        })

        self.fields['nickname'] = forms.CharField(
            required=False,
            label=False,
            widget=forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'user-nickname',
                    'placeholder': 'Username (optional)'
                }
            )
        )

    def save(self, request):
        nickname = self.cleaned_data.get('nickname')
        user = super(MyCustomSocialSignupForm, self).save(request)
        if nickname == '':
            print('no nickname set')
            user.nickname = 'no username'
            user.save()
        print('## new social user signup:', user)
        return user

class ProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nickname'].label = 'Username'

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ['nickname', 'profile_img', 'password']

# class ChangePwForm(PasswordChangeForm):
#     class Meta(Pass)

Backend/Backend/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

Backend/accounts/views.py
from django.shortcuts import render, redirect
from .forms import ProfileForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from allauth.socialaccount.forms import DisconnectForm

# Create your views here.
def profile(request):
    user = request.user
    if user.is_authenticated:
        disconnectForm = DisconnectForm(request=request)
        if request.method == 'POST':
            form = ProfileForm(instance=user, data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                return redirect('homepage')
        else:
            form = ProfileForm(instance=user)
        context = {
            'form': form,
            'disconnectForm': disconnectForm,
        }
        return render(request, 'accounts/profile.html', context)
    else:
        return redirect('account_login')

def change_pw(request):
    user = request.user
    if request.method == 'POST':
        form = PasswordChangeForm(user=user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
    else:
        form = PasswordChangeForm(user=user)
    context = {
        'form': form
    }
    return render(request, 'accounts/change_pw.html', context)

Backend/Backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Project Title</title>

  {% include 'base/_css.html' %}

  {% block head %}
  {% endblock %}
</head>
<body>
  {% include 'base/_navbar.html' %}

  {% include 'base/_messages.html' %}

  {% block content %}
  {% endblock %}

  {% include 'base/_js.html' %}

  {% block js %}
  {% endblock %}
</body>
</html>

Backend/Backend/templates/base/_css.html
{% load static %}

<!-- Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}">

<!-- font awesome -->
<script src="https://kit.fontawesome.com/d50fec281d.js" crossorigin="anonymous"></script>

<!-- my css -->
<link rel="stylesheet" href="{% static 'css/base.css' %}">

Backend/Backend/templates/base/_js.html
<!-- Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

Backend/Backend/templates/base/_messages.html
<!-- messages -->
<div class="messages messages-container">
  {% if messages %}
    {% for message in messages %}
    <div class="my-alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}
  </div>
  
  <script>
  // Remove alert after 4 seconds 
  function removeMessages() {
    setTimeout(() => {
      const messages = document.querySelectorAll('.my-alert');
      messages.forEach((message) => {
        message.remove()
      });
    }, 4000);
  }
  removeMessages();
  </script>

Backend/Backend/templates/base/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark my-navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Project name</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav d-flex justify-content-between align-items-center" style="width: 100%;">
        
        <!-- left-side-->
        <div class='d-flex'>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
        </div>

        <!-- accounts (right) -->
        <div class='d-flex'>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown me-3">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.profile_img %}
              <img class="profile-img me-2" src="{{ user.profile_img.url }}" alt="{{ user.username }}'s profile image">
              {% endif %}
              {{ user.email }}
            </a>
            <ul class="dropdown-menu profile-dropdown" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'socialaccount_connections' %}">Social Accounts</a></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <!-- <a class="dropdown-item" href="{% url 'account_logout' %}?next={{ request.path }}">Logout</a> -->
                <form method="POST" action="{% url 'account_logout' %}">
                  {% csrf_token %}
                  <button class="logout-btn" type="submit">Logout</button>
                </form>
              </li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}?next={{ request.path }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
          </li>
          {% endif %}
        </div>
      </ul>
    </div>
  </div>
</nav>

Backend/Backend/templates/homepage.html
{% extends 'base.html' %}

{% block content %}
<h1>Homepage</h1>
{% endblock %}

Backend/accounts/templates/accounts/change_pw.html
{% extends 'base.html' %}

{% block content %}
<h1>Profile</h1>
<form method="POST" action="{% url 'accounts:change_pw' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>
{% endblock %}

Backend/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Profile</h1>
<form method="POST" action="{% url 'accounts:profile' %}" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>
{% endblock %}